# Generated by Django 5.2.1 on 2025-06-03 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='administradores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuario': 'ADMIN'}, related_name='comunidades_llevadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='core.comunidad'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='propietarios',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuario': 'CLIENTE'}, related_name='inmuebles_propietario', to=settings.AUTH_USER_MODEL),
        ),
    ]
